#!/usr/bin/python3

from sys import *
from math import *
from dico import dico
from newton import newton
from secant import secant

def is_digit(n):
    try:
        int(n)
        return True
    except ValueError:
        return  False

def printhelp() :
    print("USAGE")
    print("    ./105torus opt a0 a1 a2 a3 a4 n\n")
    print("DESCRIPTION")
    print("    opt       method option:")
    print("                  1 for the bisection method")
    print("                  2 for Newton’s method")
    print("                  3 for the secant method")
    print("    a[0-4]    coefficients of the equation")
    print("    n         precision (the application of the polynomial to the solution should")
    print("              be smaller than 10ˆ-n)")

def check_error() :
    if (len(argv) < 8 or len(argv) > 8) :
        exit(84)
    for i in range (len(argv) - 1):
        if (not(is_digit(argv[i + 1]))):
            exit (84)
    if (not(argv[1] in ["1", "2", "3"])) :
        exit(84)
    if (int(argv[7]) < 0):
        exit(84)

if (len(argv) == 2 and argv[1] == "-h") :
    printhelp()
    exit(0)
check_error()
if (argv[1] == "1") :
    dico(int(argv[2]), int(argv[3]), int(argv[4]), int(argv[5]), int(argv[6]), int(argv[7])) 
if (argv[1] == "2") :
    newton(int(argv[2]), int(argv[3]), int(argv[4]), int(argv[5]), int(argv[6]), int(argv[7]))
if (argv[1] == "3") :
    secant(int(argv[2]), int(argv[3]), int(argv[4]), int(argv[5]), int(argv[6]), int(argv[7]))
